info:
  app:
    name: ${spring.application.name}

spring:
  cloud:
    consul:
    host: ${CONSUL_HOST:127.0.0.1}
    port: ${CONSUL_PORT:8500}
    discovery:
      hostname: ${spring.cloud.client.hostname}
      healthCheckPath: /actuator/health
      healthCheckInterval: 5s
      instanceId: ${spring.application.name}:${random.value}
