spring.cloud.consul.discovery.tags: version=${APP_VERSION:1.0},type=resource

zolppop.oauth.encrypt.type: RESOURCE_SERVER
zolppop.oauth.encrypt.publicKeyLocation: classpath:/adp.key
zolppop.collection.interceptors:
  - name: serviceInvokeCollection
    patterns:
      - /**